import type { ReactNode } from 'react';

export default function Footer() {
	return (
		<footer className="w-screen p-8 bg-sidebar flex flex-col gap-6 md:grid md:grid-cols-2 md:items-center">
			<FooterParagraph>
				made by <FooterLink href="https://gaby.dev">gaby</FooterLink> in Paris
				for dreamers worldwide
				<br />
				<br />
				logo shader shamelessly borrowed from{' '}
				<FooterLink href="https://latentcat.com/en">latent cat</FooterLink>
			</FooterParagraph>
			<FooterParagraph>
				none of the facts and events presented on this website are real. you are
				reading hallucinations generated by large language models.
			</FooterParagraph>
		</footer>
	);
}

function FooterLink({ href, children }: { href: string; children: ReactNode }) {
	return (
		<a
			href={href}
			target="_blank"
			rel="noreferrer"
			className="underline font-semibold hover:text-foreground focus:text-foreground transition-colors"
		>
			{children}
		</a>
	);
}

function FooterParagraph({
	children,
}: {
	children: ReactNode;
}) {
	return <p className="text-xs text-muted-foreground max-w-sm">{children}</p>;
}
