import { count } from 'drizzle-orm';
import type { ReactNode } from 'react';
import { db } from '@/db';
import { articles } from '@/db/schema/article';
import { universes } from '@/db/schema/universe';

export default async function Footer() {
	const { count: nbArticles } = await db
		.select({ count: count(articles.id) })
		.from(articles)
		.then((res) => res[0]);
	const { count: nbUniverses } = await db
		.select({ count: count(universes.id) })
		.from(universes)
		.then((res) => res[0]);

	function formatCount(number: number): string {
		return number.toLocaleString(undefined, {
			notation: 'compact',
			compactDisplay: 'short',
		});
	}

	return (
		<footer className="w-screen bg-accent mt-12 border-t border-accent-foreground/10">
			<div className="max-w-[60rem] mx-auto p-8 flex flex-col gap-6 md:grid md:grid-cols-2 md:items-start">
				<FooterParagraph>
					made by <FooterLink href="https://gaby.dev">gaby</FooterLink> in Paris
					for dreamers worldwide
				</FooterParagraph>
				<FooterParagraph>
					none of the facts and events presented on this website are real. you
					are reading hallucinations generated by large language models.
				</FooterParagraph>
				<FooterParagraph>
					logo shader shamelessly borrowed from{' '}
					<FooterLink href="https://latentcat.com/en">latent cat</FooterLink>
				</FooterParagraph>
				<FooterParagraph>
					storing <strong>{formatCount(nbArticles)}</strong> articles across{' '}
					<strong>{formatCount(nbUniverses)}</strong> universes
				</FooterParagraph>
			</div>
		</footer>
	);
}

function FooterLink({ href, children }: { href: string; children: ReactNode }) {
	return (
		<a
			href={href}
			target="_blank"
			rel="noreferrer"
			className="underline font-semibold hover:text-foreground focus:text-foreground transition-colors"
		>
			{children}
		</a>
	);
}

function FooterParagraph({ children }: { children: ReactNode }) {
	return <p className="text-xs text-muted-foreground max-w-sm">{children}</p>;
}
